{% set name = "equatable" %}
{% set version = "0.7.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: cd99f7bf79439dac5b34ccd33826aef0ef561029ecfa6d32a87c088a688ffe2b

build:
  noarch: generic
  number: 0
  script:
    - gem install --norc -l -V --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE.txt
  summary: Allows ruby objects to implement equality comparison and inspection methods.
  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/piotrmurach/equatable

extra:
  recipe-maintainers:
    - sodre
    - rluria14
    - adbeda
    - oblute
