travis:
  secure:
    BINSTAR_TOKEN: lbSzdjmx627b9dL63ppcVRkJbOwnFUAYdrSgc+xSFzeHoPpPD/yPcB+7u3AEcHQ9iEs6tW7tPawb5NIwbrRbmCs55iRf1mFrSbkJ0plfaYPAXJ3L2kzsRyU2pT23gC57CEC5ENEIle76I7rGuuhPEfhB7/EizbL0c1C38Vu4VjLGXShgJkW7BFMPUP5Ftqo+IjPuA+p5fuQ1Q4W3TRDCpit2qu6d6IwRdGd5TITKpDFZNQhJVct4swUe02QGdH8b0g7z9XNu8XSOF5nZ3UDNTObElAznbgx/VFJw1ot2ZTNnkVnczHMpYsO5m8ndgIE49WRi67Wf+fCEKFCkR4TD7KaWQqRKkA/pkQwPjBciFQ1Vn31hfIUMfm95fYndQr/Bk+oDEqFRLR6UHYpWhtMMhOhqLnxZKwWPA/lnnY/a1EC+PahnrsAQJWNoRjy+s2glvaLYvhjhFw88d5hj1z9M0h09H/mvKdcNxFcubiOyusV2WlFpHoeNA/tpPx2Jk/FGrrOaUmF1tX5K39p/8oLEgzxFLrS1bIa5u1xBMc4Gb5iwjWEM097YDwQ3Hum21GobnwElQxgfom1E53cwgiW682SWN9xDNgxdAEv1WxbZKL5ck0s96bG/vMBNDFgsJ7yfvxcvuwosg0+emfXv+jU5RDsOeAzWYcZE2NIbjHMPpbg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
